"""Small storage layer over SQLite or PostgreSQL, so a service runs the same SQL on either.

    Database("inventory.db", SCHEMA)                                   SQLite file (development, tests)
    Database(":memory:", SCHEMA)                                       SQLite in memory (tests)
    Database("postgresql://user:pw@db/smartshopping", SCHEMA, schema="inventory")   PostgreSQL

SQL is written once in the subset both understand: "?" placeholders, "ON CONFLICT ... DO NOTHING",
"RETURNING". The table definitions use SQLite's "INTEGER PRIMARY KEY AUTOINCREMENT", which is
translated for PostgreSQL. Each PostgreSQL service keeps its tables in its own schema of the shared
database.

One connection is shared by the whole service, so a lock lets one transaction (or query) use it at a
time. That keeps every transaction all-or-nothing and isolated from requests running in other threads.
A dropped PostgreSQL connection (database restart, network blip) is reopened and the statement tried
again, but only when nothing has been written yet: a read, or the BEGIN that starts a transaction. A
connection lost in the middle of a transaction is reported as an error; the transaction never committed.

The same file is used by services/inventory and services/payments; keep the copies identical.
"""

import re
import sqlite3
import threading
from contextlib import contextmanager
from typing import Dict, List, Optional, Sequence, Tuple

AddedColumns = Dict[str, List[Tuple[str, str]]]


def is_postgres(url: str) -> bool:
    return url.startswith(("postgresql://", "postgres://"))


def _is_connection_error(e: Exception) -> bool:
    import psycopg
    return isinstance(e, (psycopg.OperationalError, psycopg.InterfaceError))


class _PgCursorAdapter:
    """Lets the service's "?" SQL run on psycopg, which uses "%s"."""

    def __init__(self, conn):
        self._conn = conn

    def execute(self, sql: str, args: Sequence = ()):
        return self._conn.execute(sql.replace("?", "%s"), tuple(args))


class Database:
    def __init__(self, url: str, schema_sql: str, schema: str = "public",
                 added_columns: Optional[AddedColumns] = None):
        self.url = url
        self.postgres = is_postgres(url)
        self.schema = schema
        self._lock = threading.RLock()
        self._schema_sql = schema_sql
        self._added_columns = added_columns or {}
        self.conn = None
        self._connect()
        self._create_tables()

    # ------------------------------------------------------------------ setup

    def _connect(self) -> None:
        if self.postgres:
            import psycopg
            from psycopg.rows import dict_row
            if not re.fullmatch(r"[a-z_][a-z0-9_]*", self.schema):
                raise ValueError(f"Invalid schema name {self.schema!r}")
            self.conn = psycopg.connect(self.url, autocommit=True, row_factory=dict_row)
            self.conn.execute(f"CREATE SCHEMA IF NOT EXISTS {self.schema}")
            self.conn.execute(f"SET search_path TO {self.schema}")
        else:
            # One shared connection keeps ":memory:" databases alive for tests.
            self.conn = sqlite3.connect(self.url, check_same_thread=False, isolation_level=None)
            self.conn.row_factory = sqlite3.Row
            self.conn.execute("PRAGMA foreign_keys = ON")
            if self.url != ":memory:":
                self.conn.execute("PRAGMA journal_mode = WAL")

    def _create_tables(self) -> None:
        with self._lock:
            if self.postgres:
                ddl = self._schema_sql.replace("INTEGER PRIMARY KEY AUTOINCREMENT",
                                               "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
                self.conn.execute(ddl)
                for table, columns in self._added_columns.items():
                    for name, decl in columns:
                        self.conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {name} {decl}")
            else:
                self.conn.executescript(self._schema_sql)
                for table, columns in self._added_columns.items():
                    have = {r["name"] for r in self.conn.execute(f"PRAGMA table_info({table})")}
                    for name, decl in columns:
                        if name not in have:
                            self.conn.execute(f"ALTER TABLE {table} ADD COLUMN {name} {decl}")

    def _ensure_connected(self) -> None:
        if self.postgres and (self.conn.closed or self.conn.broken):
            self._connect()

    def _retry_once(self, fn):
        """Run fn; if the PostgreSQL connection had dropped, reconnect and run it once more."""
        self._ensure_connected()
        try:
            return fn()
        except Exception as e:
            if not (self.postgres and _is_connection_error(e)):
                raise
            self._connect()
            return fn()

    def _cursor(self):
        return _PgCursorAdapter(self.conn) if self.postgres else self.conn

    # ---------------------------------------------------------------- queries

    @contextmanager
    def tx(self):
        """All-or-nothing. Inside, use c.execute(sql, args); results have fetchone/fetchall/rowcount."""
        with self._lock:
            self._retry_once(lambda: self.conn.execute("BEGIN" if self.postgres else "BEGIN IMMEDIATE"))
            try:
                yield self._cursor()
                self.conn.execute("COMMIT")
            except Exception:
                if not (self.postgres and self.conn.broken):
                    self.conn.execute("ROLLBACK")
                raise

    def one(self, sql: str, args: Sequence = ()) -> Optional[dict]:
        with self._lock:
            row = self._retry_once(lambda: self._cursor().execute(sql, args).fetchone())
            return dict(row) if row else None

    def all(self, sql: str, args: Sequence = ()) -> List[dict]:
        with self._lock:
            return [dict(r) for r in self._retry_once(lambda: self._cursor().execute(sql, args).fetchall())]

    def drop_schema(self) -> None:
        """Tests only: remove this service's PostgreSQL schema and everything in it."""
        if self.postgres:
            with self._lock:
                self.conn.execute(f"DROP SCHEMA IF EXISTS {self.schema} CASCADE")
